# Generated by Django 4.1 on 2022-09-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
