# Generated by Django 4.1 on 2022-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_watchlist_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='owner',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
