# Generated by Django 4.1 on 2022-10-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='currentprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
