# Generated by Django 4.1 on 2022-10-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='currentbid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
