# Generated by Django 4.1 on 2022-10-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listings_currentbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='currentbid',
            field=models.CharField(max_length=200),
        ),
    ]
