# Generated by Django 4.1 on 2022-10-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_remove_listings_currentbid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=200)),
            ],
        ),
    ]
